### PR TITLE
Fix compilation errors for ros2 client on Foxy

### LINKED ISSUE #110: free_fleet_client_ros2 build fails for Foxy
### Required information:

- Operating system and version:
  - Ubuntu 20.04 
- ROS distribution and version:
  - Foxy 
- ROS installation type:
  - Binary 
- Package or library, if applicable:
  - Free Fleet 

### Description of the bug

Not able to compile the Free Fleet Client ROS2 pkg

### Steps to reproduce the bug

1. clone the free_fleet repo in the colcon_ws/src
2. build using colcon build

**std err log file** 

[stderr.log](https://github.com/open-rmf/free_fleet/files/7635356/stderr.log)

### Expected behavior

Build Success

### Actual behavior

Build Failed

### PR DESCRIPTION
**Pull request by eliasdc**
### Fixed bug

Fixes #110, #111 

### Fix applied

Reverted back to default parameters when declaring each parameter to support Foxy builds. This results in a slight behavior change where you're now able to run the node without setting any parameters.

Added an additional fix where it was comparing or calculating with two timestamps with different clock types resulting in a crash. The solution correctly sets the `ROS_TIME` clock type when adding the location to the robot path.

### CODE REVIEW

**Comment by aaronchongth** [comment]
Thanks for making the changes! The build works fine for me too, however I am having some trouble running the turtlebot3 simulation example. Trying to figure out what changed with nav2 between Foxy and Galactic, other than the rmw

**Comment by eliasdc** [comment]
@aaronchongth quite a lot has changed in nav2 Galactic. I remember having lots of configuration conflicts/mistakes, e.g. some recovery services changed names.

**Comment by aaronchongth** [comment]
@eliasdc Thanks for confirming. Since that remaining part is just for launching an example, it be a better idea to have this merged and comment in documentation that the example works for Galactic only

**Review by aaronchongth — APPROVED** [review]
Thanks for getting the Foxy build working!

**Pull request merged**
