### PR TITLE
Fix compilation errors for ros2 client on Humble

### PR DESCRIPTION
**Pull request by eliasdc**
### Fix applied

response callback signature updated to support galactic and humble. I don't believe this builds on Foxy (haven't tested it).

### CODE REVIEW

**Review by aaronchongth — APPROVED** [review]
Thanks for the fix!

**Review by aaronchongth — CHANGES_REQUESTED** [review]
You would need to sign your commits with GPG before I can merge it, thanks!

Regarding Foxy support, it should not be too big a concern, if anyone requires it, I can create a foxy branch.

**Comment by aimethierry** [comment]
> You would need to sign your commits with GPG before I can merge it, thanks!
> 
> Regarding Foxy support, it should not be too big a concern, if anyone requires it, I can create a foxy branch.

I am using Foxy, however i can compile and run, but the goal is being rejected by the server

**Comment by aaronchongth** [comment]
Could you provide more information about the rejection? Namely
* Was it an error or did nothing happen?
* How does the server log look like?
* How does the client log look like?
* What is your setup currently? (OS, version of ROS, simulation or real robot)

**Comment by aimethierry** [comment]
at the moment nothing is happening and i am using 
Ubuntu 20.04
Ros2 foxy 
simulation

**Comment by aaronchongth** [comment]
Could you provide more information for me to try to re-create the issue? What steps have you run, was the goal through `nav2` or a free fleet request?

**Comment by aaronchongth** [comment]
Thanks for the information @aimethierry.

For long logs, please use https://gist.github.com, or 
```
code blocks
```

This has grown out of the scope of this PR, please continue the conversation in https://github.com/open-rmf/free_fleet/issues/113, or try out the fixes mentioned in that thread.

**Pull request merged**
